### ISSUE TITLE
FloatingSearchview Suggestion not displaying content

### ISSUE THREAD

**Issue by timoshimmo** [arimorty/floatingsearchview#107]
Hello there, 
I successfully implemented the floatingsearchview widget and added the desired available styles to it. The only issue is the suggestions dropdown works it drops down but displays nothing. If i click on it, it shows a result in the searchbox but the history icon and text are not visible.

**Comment by arimorty** [comment]
Hi @timoshimmo ,

First of all, if you don't know it already, the history icon doesn't come with the library out of the box, please have a look at the   [sample code](https://github.com/arimorty/floatingsearchview/blob/master/sample/src/main/java/com/arlib/floatingsearchviewdemo/MainActivity.java#L241) on how to add it. For your other problem, we need to see what your styling looks like in order to have a sufficient understanding of the problem.

**Comment by timoshimmo** [comment]
Okay will try that and get back to you. Thanks alot for the swift answer.

**Comment by timoshimmo** [comment]
Thanks for your help it works now
