### ISSUE TITLE
FloatingSearchView in the middle of the screen

### ISSUE THREAD

**Issue by Komatoz** [arimorty/floatingsearchview#117]
Hi! 

I want to place FloatingSearchView in the middle of the screen properly (inside fragment, Relative Layout)

That - FloatingSearchView appears only at the top:

```
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_centerVertical="true"
```

That -  when focus, fading zone is only 60 dp, not full screen 

```
        android:layout_width="match_parent"
            android:layout_height="60dp"
            android:layout_centerVertical="true"
```

How to do that properly?

**Comment by arimorty** [comment]
Hi @Komatoz , 

As stated [here](https://github.com/arimorty/floatingsearchview/blob/master/README.md#usage), You need to set the height of the `FloatingSearchView` to match where you want the fade and/or suggestions to appear. The suggestions will not extend outside of the view's bound, you have to make sure it has the room it needs for the suggestions. 

The library can be very flexible, but I see that some developers have trouble configuring it in various ways. Because of that, I want to start a new blog where I would show in a step-by-step fashion how to implement different configurations/scenarios. This will serve as a kind of documentation for people using or trying to use this library.

What do you think? Would you want your case to be the first one that I will write how to implement?

If you do, please provide me with enough details of what you want to achieve so that I can write an example that you and others will benefit from. To be clear, I am not asking for any detailed info about what you are building, I just need a clear understanding of what you want to achieve.

**Comment by Komatoz** [comment]
Thank you for answer! 

> What do you think? Would you want your case to be the first one that I will write how to implement?

It would be nice! 

I want to make something like this 
![device-2016-08-16-122901](https://cloud.githubusercontent.com/assets/6008311/17692927/23a1d59c-63a5-11e6-80bd-eb72cf4ab2ab.png)

And this when FloatingSearchView is in focus
![device-2016-08-16-123048](https://cloud.githubusercontent.com/assets/6008311/17692999/82160242-63a5-11e6-8224-027038a545ec.png)

**Comment by arimorty** [comment]
Hi @Komatoz , here is the blog post explaining how to achieve what you need. [https://arimorty.github.io/tags/#floating-search-view](https://arimorty.github.io/tags/#floating-search-view)

I hope it helps and others.

**Comment by Komatoz** [comment]
Thank you for your post! 

But i didn't understand where I should place methods onFocus() and  onFocusCleared(). Could you help me?

**Comment by arimorty** [comment]
You're welcome! 

The sample app contains the source code for the example in the post. More specifically, look at this https://github.com/arimorty/floatingsearchview/blob/master/sample/src/main/java/com/arlib/floatingsearchviewdemo/fragment/SlidingSearchViewExampleFragment.java#L138

**Comment by Komatoz** [comment]
I implemented your hack, thank you so much!

Is it possible to use not fixing value for header_view and android:translationY? For example to place the Search View right in the middle of any screens?
