### ISSUE TITLE
listener for suggestion right icon?

### ISSUE THREAD

**Issue by Derek-X-Wang** [arimorty/floatingsearchview#14]
Hi @arimorty,

Is there any way we can customize the onclick behavior of the suggestion right icon?
Or is there a way to remove/disable that icon?

Thanks

**Comment by arimorty** [comment]
Hi @arimorty,

Since the right icon has a clearly defined goal (to move the suggestion to the search box) I do not intend to provide onClick customization at the moment. For your second question, it should indeed be possible to do it, so I will probably add it in the next release.

 In the meanwhile, since I don't know when next release is going to happen, you can perhaps set the right icon's color to transparent like:

`app:floatingSearch_suggestionRightIconColor="#00000000"` But keep in mind, it won't do for clicks which will still move the text up.

**Comment by Derek-X-Wang** [comment]
Thanks for your reply :)
