### ISSUE TITLE
Changing on pressed colors

### ISSUE THREAD

**Issue by Michael1009** [arimorty/floatingsearchview#162]
How do I customize the on pressed colors? I am inflating the search bar as a header in my ListView and when I press it, it makes the background gray. I would like to have the background stay white when search bar is selected. Is there a way to do this?

**Comment by masoudfcr** [comment]
you have to change it in colors.xml resource file, change colorBackgroundHighlightWhite to the color u want

**Comment by bhm** [comment]
@masoudfcr I do not believe this is the solution at all. Furthermore there is no such field in the whole library. At least I cannot find one.

@Michael1009 9 days has passed. If my understanding is right, you want to turn off the background dimming via `floatingSearch_dimBackground` option. 

@arimorty This is a bug in the library I believe since you are always setting 150 alpha (to the `Drawable mBackgroundDrawable`  when dimming is turned on. Which should be 50, or up to change via an xml option.

**Comment by masoudfcr** [comment]
@bhm well it works for me, I meant u should change the source of the library, find colorBackgroundHighlightWhite in colors.xml under the values folder and simply change it to what ever color u want.

**Comment by Michael1009** [comment]
@bhm thank you for the answer! It works and the issue is resolved.
