### ISSUE TITLE
Cannot toggle search focusable state

### ISSUE THREAD

**Issue by Permusoft** [arimorty/floatingsearchview#174]
I can disable the "search focusable" state using FloatingSearchView#setSearchFocusable(), but it will not re-enable. See Feb 3 revisions of my _[FSV Icon Bug Demo](https://github.com/Permusoft/FSV-Icon-Bug-Demo)_.

**Comment by Permusoft** [comment]
I would like to help out -- if you make a suggestion I can do some work here!

**Comment by arimorty** [comment]
Sure, @Permusoft thanks! let me take some time now and look into it. I didn't have time to maintain this library lately ): I promise to respond today this time.

**Comment by arimorty** [comment]
Ok @Permusoft the issue is with a missing call to `setFocusableInTouchMode(isFocusable)` in [ setSearchFocusable](https://github.com/arimorty/floatingsearchview/blob/master/library/src/main/java/com/arlib/floatingsearchview/FloatingSearchView.java#L1110) 

It would be great if you can submit a PR for that. But make sure the PR is clean and doesn't do any secondary things.

Looking forward to merge your PR.
Thanks for helping out!

**Comment by Permusoft** [comment]
What is the build procedure?

**Comment by arimorty** [comment]
I am not sure I understand what you mean by build procedure, but [here](https://guides.github.com/activities/contributing-to-open-source/) is a guide for how to submit PRs

**Comment by Permusoft** [comment]
How do you compile the library?

**Comment by arimorty** [comment]
You just fork or download and there is a sample app that will compile the library when you run it from Android Studio.

**Comment by Permusoft** [comment]
I think my first import into Studio was messy. I started over and it seems better.

**Comment by Permusoft** [comment]
Are you willing push a new version to Maven?
