### ISSUE TITLE
clearQuery() is not working

### ISSUE THREAD

**Issue by vikramezhil** [arimorty/floatingsearchview#175]
I am having some trouble in automatically clearing the search view **query text** once the user searches the query.

I tried **clearQuery()** and even manually tried using **setSearchText("")** at both **onFocusCleared()**  and **onSearchAction()** but the search view doesn't clear the text unless it is focussed again.

Any way of achieving this along with making the search view stay focussed and prevent the keyboard from closing so the user can continue inputing multiple search queries?

**Comment by arimorty** [comment]
Hi @vikramezhil , you are absolutely correct about the confusion, will try to add docs. But, instead of using `setSearchText("")` in `onFocusCleared() ` use `setSearchBarTitle("")`. When the search isn't focused, you are dealing with the search view title, not query (hence the reason clearQuery() is not working for you) look at the method comments in the code of the library to get a better understanding.

For the second part, currently this library doesn't support it. But, I'll add it to the next build because I thing it's a good feature to have. 

Thanks,
Ari

**Comment by vikramezhil** [comment]
@arimorty The setSearchBarTitle("") solution works great, any timeline on the enhancement request? 

Thanks,
Vikram
