### ISSUE TITLE
No way for search suggestion customization

### ISSUE THREAD

**Issue by jakubkrolewski** [arimorty/floatingsearchview#30]
I can't find any way of changing the layout of the search suggestion item. I tried the following:
- providing a custom suggestions adapter - not possible
- providing a custom layout for the adapter - not possible
- setting a custom text in onBindSuggestion(...) method - not possible
- returning a styled text from the SearchSuggestion#getBody() method - not possible (the returned type is String)

Could you change the library API to allow for any customization from the list above?

**Comment by arimorty** [comment]
I completely empathizes with you... The reason is that the library needs to know the height of each suggestion dynamically in order to determine total suggestion list height dynamically. I might update it, but not sure when. Anyway, it will require a lot of changes in order to support what you want.

**Comment by arimorty** [comment]
With the new release (2.0.1), there is a lot more that you can do in onBindSuggestion(). You can essentially customize the TextView that holds the suggestion. For example, you can change size, color, font, use Html.fromHtml() with it, etc.
