### ISSUE TITLE
Right to left support

### ISSUE THREAD

**Issue by mehrdad-shokri** [arimorty/floatingsearchview#36]
Hello,Tnx for your nice library. I've got a question. 
The library is working is right in left to right languages. 
But if the input language is changed to a rtl language like Persian, although text goes to right,  

But the query is shown under the clear button. I submit a screen shot for you.
How do I solve this problem.

![device-2016-03-12-191337](https://cloud.githubusercontent.com/assets/13661520/13723851/d79428e2-e886-11e5-8e1d-7dc2e35ffabb.png)

**Comment by mehrdad-shokri** [comment]
any support?

**Comment by arimorty** [comment]
Hi @mehrdaad 

Unfortunately, this library does not support RTL at the moment, I might add it in the future, but I can't say when exactly.

**Comment by mehrdad-shokri** [comment]
@arimorty tnx for answer. I think If you add a 48dp padding to right for `mSearchInput` in the `FloatingSearchView` class the problem would be solved.I forked the project. but I don't know how to publish the lib so I can install it for my self.

**Comment by arimorty** [comment]
Actually, I started implementing it at some point, but it turned out to be more involved than I had expected and I didn't have time. My point is that I am very familiar with this lack of support and I hope to start working on it in the future. Anyways, good luck figuring it out yourself and don't forget to issue a pull request if you figure it out.
