### ISSUE TITLE
getQuery() not working.

### ISSUE THREAD

**Issue by zijianwang90** [arimorty/floatingsearchview#42]
Hi there,

I tried to searchView.getQuery() in FloatingSearchView.OnSearchListener. But it's not working (returns an empty String ""), which is wired. I looked into the source code and can't figure out why.

**Comment by peshkira** [comment]
It is because in line [620](https://github.com/arimorty/floatingsearchview/blob/master/library/src/main/java/com/arlib/floatingsearchview/FloatingSearchView.java#L620) in the FloatingSearchView the focus is removed from the search view before calling the installed listener.

When you look at the method implementation of `setSearchFocusedInternal(boolean focused)` on line [1366](https://github.com/arimorty/floatingsearchview/blob/master/library/src/main/java/com/arlib/floatingsearchview/FloatingSearchView.java#L1366), you will see that the EditText mSearchInput is set to an empty string and `getQuery()` returns the text of the EditText.

**Comment by arimorty** [comment]
fix mentioned here https://github.com/arimorty/floatingsearchview/issues/43 will be implemented in next version (2.2.0)
