### ISSUE TITLE
FloatingSearchView text is white

### ISSUE THREAD

**Issue by Pabloku** [arimorty/floatingsearchview#5]
Hi!

I am trying to implement this cool FloatingSearchView but it just shows me white text when writting! Hint is shown correctly but it seems that the edittext text is in white color. I have tried to styled it without success. Any help?

Thanks very much!

**Comment by arimorty** [comment]
Hi, 

The EditText's text color is controlled by the style of your app's EditTexts which you can control in your theme with attribute <item name="android:editTextStyle"/> or <item name="editTextStyle"/> (for appCompat).

The reason the hint is showing is because, at this point, floatingSearchView sets  the color for the hint, but the search color is controlled by you. So it must be something in your styles.

As a side note, this lib is in its infancy and is continually evolving, so I would suggest checking it out for updates regularly.

**Comment by Pabloku** [comment]
Thanks @arimorty! You were right!
