### ISSUE TITLE
Margin/padding issue

### ISSUE THREAD

**Issue by manufunk** [arimorty/floatingsearchview#95]
I don't know how to get rid of the border or margin or padding. I would like to make this fit to the latest android style guide and there is no grey space around the navigation bar.

![image](https://cloud.githubusercontent.com/assets/16864103/16925964/fe1ed048-4d26-11e6-8046-83cc11cd8105.png)

**Comment by joydeepsaha05** [comment]
@Manu206 Could you post your layout file?

**Comment by ericntd** [comment]
For me the issue there seems to be too much space between the left action icon and the text input cursor.
(The same for the suggestion history icon and the text)
![screen shot 2016-08-16 at 11 45 17 am](https://cloud.githubusercontent.com/assets/19919208/17687396/35affd02-63a7-11e6-9f07-6624758c5b19.png)

Is there a way to reduce it?

**Comment by n-belokopytov** [comment]
I would like to state the same thing as the poster ericn37 - there is too much space between the left icon and text. I would like to manipulate that.

**Comment by mithleshjs** [comment]
Here's how I changed the margin : 
```java
FloatingSearchView mSearchView = (FloatingSearchView)findViewById(R.id.floating_search_view);

FrameLayout.LayoutParams params = new FrameLayout.LayoutParams(ViewGroup.LayoutParams.WRAP_CONTENT, ViewGroup.LayoutParams.WRAP_CONTENT);
        
params.rightMargin = (int)getResources().getDimension(R.dimen.search_icon_margin);

ImageView search_icon = (ImageView)mSearchView.findViewById(R.id.left_action);

search_icon.setLayoutParams(params);
```

**Comment by arimorty** [comment]
I would suggest to import the source to your library and change around margins as needed. We try to only have general features, because some devs will always have custom needs and we prefer to focus on stability instead of constantly adding features. 

You can also extract views and manipulate them programmatically like @mithleshjs 's comment, but I personally think it can result in messy code.

Thanks, Ari.
